### ISSUE TITLE
JavaScript not run; JavaScript variables in CSS not rendered

### ISSUE THREAD

**Issue by AMDphreak** [searKing/preview-vscode#108]
This plugin is useless for modern testing needs, because it does not render any CSS that uses JavaScript variables.

I am designing a page that uses a script tag at the end of the page to apply some visual effects. The javascript populates variables that are used in the CSS of the file. The CSS is in a separate file.

This seems like a pretty big gap in the implementation.

Your plugin's Preview:
![Image](https://github.com/user-attachments/assets/33734d81-a6c5-462a-92ec-2d29f1c9a49b)

The real page: 

![Image](https://github.com/user-attachments/assets/24454123-88c7-4daa-abe7-415cbe51f9ad)
The color changes as I move the mouse around.

The example javascript:
```javascript
    <script>
        document.addEventListener('mousemove', (e) => {
            const x = e.clientX;
            const y = e.clientY;
            document.documentElement.style.setProperty('--mouse-x', `${x}px`);
            document.documentElement.style.setProperty('--mouse-y', `${y}px`);
        });
    </script>
```

The example CSS using the javascript variables:

```css
.gradient-animation {
    background: radial-gradient(circle at var(--mouse-x) var(--mouse-y), rgb(255 255 255 / 0%), 75%, rgb(191 70 0 / 41%));
    mix-blend-mode: hard-light;
    pointer-events: none;
}
```

An example HTML, so you can test this out yourself:

```html
    <div class="static-gradient"></div>
    <div class="gradient-animation"></div>
```

Add this CSS for the static-gradient:

```css
.static-gradient {
    background:
        radial-gradient(circle at bottom, transparent, 90%, rgba(0, 0, 0, 0.5)), /* Dark region at the top */
        radial-gradient(circle, #f1f1f1, #05ab75),
        aliceblue;
}
```

Also, interesting to note, your preview throws in an entire extra amount of space at the end of the page, defeating the ability to test at different page lengths:

![Image](https://github.com/user-attachments/assets/a29ab357-0b58-484d-9011-e289ab626f93)
